name: Release
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release
        run: git config --global user.email "ruimo.uno@gmail.com" &&
          git config --global user.name "Shisei Hanai" &&
          gradle release -Prelease.useAutomaticVersion=true

