name: Snapshot Build
on:
  push:
    branches:
    - main

env:
  PKG_TOKEN: ${{secrets.PKG_TOKEN}}

jobs:
  build-snapshot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
